annotations:
  category: DeveloperTools
apiVersion: v2
appVersion: 20.0.3.1674047714
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts/postgresql
    version: 12.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
description: Keycloak is a high performance Java-based identity and access management solution. It lets developers add an authentication layer to their applications with minimum effort.
engine: gotpl
home: https://www.keycloak.org
icon: https://bitnami.com/assets/stacks/keycloak/img/keycloak-stack-220x234.png
keywords:
  - keycloak
  - access-management
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: keycloak
sources:
  - https://github.com/bitnami/containers/tree/main/bitnami/keycloak
  - https://github.com/keycloak/keycloak
version: 20.0.1674047714
